### ISSUE TITLE
com.mirantis.mk.Ssh.getKnownHost Failure

### ISSUE THREAD

**Issue by tgerdes** [Mirantis/pipeline-library#1]
When mirroring/cloning a repo to a targetURL like `ssh://admin@10.167.4.90:29418/mk/mk-pipelines`
The regex in getKnownHost [1] incorrectly matches this as a "git@github.com:organization/repository like URL", and follows the first branch that sets the port to 22 instead of the port from the URI.

The key for the ssh server running on port 22 will be added, not the key for the server on port 29418.  Later when a git clone/fetch occurs, there will be an error:
```
+ git remote update --prune
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch target
```

[1] https://github.com/Mirantis/pipeline-library/blob/master/src/com/mirantis/mk/Ssh.groovy#L22

**Comment by fpytloun** [comment]
Fixed, thank you for reporting.
