### ISSUE TITLE
com.mirantis.mk.Ssh.prepareSshAgentKey pgrep failure

### ISSUE THREAD

**Issue by tgerdes** [Mirantis/pipeline-library#2]
When running the git-mirror-pipeline, the pgrep command in com.mirantis.mk.Ssh.prepareSshAgentKey [1] errors because $USER is not defined.

```
[Pipeline] sh
[source] Running shell script
+ pgrep -l -u -f ssh-agent$
pgrep: invalid user name: -f
```
The pipeline does not fail at this point, the scripts continue to run beyond this step.
I'm not sure if this is environmental in my deployment or something wrong with the script.

[1] https://github.com/Mirantis/pipeline-library/blob/master/src/com/mirantis/mk/Ssh.groovy#L83

**Comment by fpytloun** [comment]
Fixed
